FROM alpine:3.19.0@sha256:51b67269f354137895d43f3b3d810bfacd3945438e94dc5ac55fdac340352f48

RUN apk add bash shadow sudo
RUN apk add cmake make libc-dev
RUN apk add gcc g++
RUN apk add nodejs npm
RUN apk add clang17 clang17-analyzer clang17-extra-tools compiler-rt llvm17
RUN apk add git valgrind file
RUN apk add openjdk21-jre-headless
RUN apk add libev-dev
RUN apk add ada-static ada-dev
RUN apk add sqlite-dev sqlite-static sqlite3pp
RUN apk add nlohmann-json

RUN \
    groupadd --gid 1000 vscode && \
    useradd -s /bin/bash --uid 1000 --gid 1000 -m vscode && \
    echo "vscode ALL=(root) NOPASSWD:ALL" > "/etc/sudoers.d/vscode" && \
    chmod 0440 "/etc/sudoers.d/vscode"

WORKDIR /usr/src

RUN \
    git clone https://github.com/nodejs/llhttp.git --depth 1 -b v9.1.3 && \
    cd llhttp && \
    npm install && \
    sed -i 's/$(INSTALL) -C /$(INSTALL) -c /g' Makefile && \
    make release RELEASE="9.1.3" && \
    cmake -S release -B releasebuild -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON && \
    cmake --build releasebuild && \
    cmake --install releasebuild

WORKDIR /
