on:
  check_run:
  check_suite:

jobs:
  debug:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
