name: Interesting Test

on:
  pull_request:
    branches:
      - master_clone

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Run test
        run: exit 0
